10-sprint filmorate
Victor-Ogurtsov/java-filmorate pull request #5
Opened 2024-04-29 08:29 UTC by Victor-Ogurtsov

2024-04-29 12:36 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-04-29 12:36 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/ValidationException.java
> +public class ValidationException extends RuntimeException {
это давайте в отдельный пакет exception

2024-04-29 12:36 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/BaseController.java
> +public class BaseController<T> {
отлично

2024-04-29 12:36 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    String name;
модификаторы доступа добавьте

2024-04-29 12:36 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    Long id;
модификаторы доступа добавьте

2024-04-29 12:36 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        } else if (!user.getEmail().contains("@")) {
все круто, давайте попробуем вместо этого метода сделать задание со * -- через аннотации.
Если решите не делать, то переименуйте метод в validate

2024-04-30 08:30 UTC, Victor-Ogurtsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null) {
Добрый день, но разве при изменении объекта [@PutMapping public User updateUser(@RequestBody User user) {...]
переданный объект  User user не может содержать дату дня рождения измененную на неправильную или имя равное null? 

Ведь перенеся эти проверки из метода checkUser(User user) в метод addUser, мы пропустим эти сценарии в updateUser?

2024-04-30 08:44 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null) {
держать эту логику в checkUser неправильно, так как checkUser должен проверять и если что то не то, кидать ошибку. Но ничего не менять.
Эту логику вы можете перенести в другой приватный метод и вызывать его в addUser и updateUser. Метод можно назвать setUserName

2024-04-30 11:27 UTC, ErkinKasymaliev commented on src/test/java/ru/yandex/practicum/filmorate/controllerTests/FilmControllerTest.java
> -    @Test
почему удалили тесты? перестали проходить после того как добавили @Valid? если да, то надо:
`Assertions.assertThrows(ValidationException.class, () -> filmController.addFilm(film), "Не выброшено исключение на пустое имя");` --здесь  ValidationException.class поменять на MethodArgumentNotValidException.class. Это спринговское исключение которое по дефолту выбрасывает spring-validation. В следующем задании вы научитесь оборачивать такое в кастомные исключения.
Поправьте во всех тестах которые удалили

2024-05-01 07:22 UTC, Victor-Ogurtsov commented on src/test/java/ru/yandex/practicum/filmorate/controllerTests/FilmControllerTest.java
> -    @Test
Добрый день, на вебинаре наставник объяснял, что в этом спринте требуется сделать тесты для бизнес логики, как бы без запросов, и что остальное будем покрывать тестами следующих спринтах. Действительно после аннотации @Valid поломались тесты. 

Тут, если я правильно понял, нужно создавать http запрос в тесте, чтобы выловить MethodArgumentNotValidException.class? Просто созданием объекта filmController и добавлением неправильного аргумента в addFilm(film) это исключение вызвать не смогу?

2024-05-01 09:59 UTC, ErkinKasymaliev commented on src/test/java/ru/yandex/practicum/filmorate/controllerTests/FilmControllerTest.java
> -    @Test
```
void shouldThrowValidationExceptionThenAddNewFilmAndNameIsBlank() {
        Film film = new Film(null, "", "description", "1895-12-28", 40);

        Assertions.assertThrows(MethodArgumentNotValidException.class, () -> filmController.addFilm(film), "Не выброшено исключение на пустое имя");
}
```
вот так. 
у вас стоит @NotBlank в модели, это аннотация spring-а, которое бросает MethodArgumentNotValidException.class. Вот это исключение вам и надо словить

2024-05-21 17:44 UTC, merged