11-sprint-add-friends-likes
Victor-Ogurtsov/java-filmorate pull request #6
Opened 2024-05-26 09:26 UTC by Victor-Ogurtsov

2024-05-26 09:53 UTC, ErkinKasymaliev requested changes
привет, хорошая работа!
оставил комменты

2024-05-26 09:53 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void checkFilm(Film film) {
его сделайте private, ведь используете его только здесь

2024-05-26 09:53 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public boolean idIsPresent(Long id) {
избыточный метод, просто используйте films.containsKey

2024-05-26 09:53 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public boolean idIsPresent(Long id) {
избыточный метод, просто используйте users.containsKey

2024-05-26 14:34 UTC, Victor-Ogurtsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public boolean idIsPresent(Long id) {
Привет! Мне показалось это разумным. Я пока не очень понимаю, как буду проверяться наличие фильма с ID в хранилище с другой реализацией (не в памяти ПК), и наверное может в метод интерфейса "idIsPresent" можно будет вставить логику других реализаций хранилищ. А тут вроде идет привязка к HashMap и contains?

Получается, что убрав этот метод мне нужно получить Map c фильмами, чтобы использовать contains. И тогда Я добавляю геттер поля Map<Long, Film> films и в реализацию InMemoryFilmStorage и в интерфейс FilmStorage? Вроде кода получается столько же или я преимущества не понимаю?

2024-05-26 14:41 UTC, Victor-Ogurtsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public boolean idIsPresent(Long id) {
У меня есть метод public Collection<Film> getAllFilms() { return films.values(); }
Наверное можно через stream пройтись по всему списку объектов film и проверить совпадение по id, но вроде плохо каждый раз перебирать весь список.

2024-05-26 17:17 UTC, ErkinKasymaliev requested changes

2024-05-26 17:17 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public boolean idIsPresent(Long id) {
вот ваш метод 
```
public boolean idIsPresent(Long id) {
   return films.containsKey(id);
}
```
вот зачем в отдельный метод убирать одну строку? Одно дело если бы там вы использовали логику побольше, что мешает там где вы вызываете idIsPresent, просто вызывать films.containsKey(id)?

2024-05-26 17:17 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public boolean idIsPresent(Long id) {
> У меня есть метод public Collection getAllFilms() { return films.values(); } Наверное можно через stream пройтись по всему списку объектов film и проверить совпадение по id, но вроде плохо каждый раз перебирать весь список.

не надо

2024-05-26 17:17 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public boolean idIsPresent(Long id) {
> Я пока не очень понимаю, как буду проверяться наличие фильма с ID в хранилище с другой реализацией (не в памяти ПК), и наверное может в метод интерфейса "idIsPresent" можно будет вставить логику других реализаций хранилищ.

пока об этом не думайте, вам позже объяснят когда начнете проходить базу данных

2024-05-26 17:53 UTC, Victor-Ogurtsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public boolean idIsPresent(Long id) {
Хорошо, но у меня в классе "FilmService" нет доступа к мапе "films". Вижу два пути:
1) Изменить в классе "InMemoryFilmStorage" метод "Collection<Film> getAllFilms() { return films.values(); }"
 на метод " Map<Long, Film> getFilms() { return films; }.
 
 2) Добавить в классе "InMemoryFilmStorage" и интерфейсе "FilmStorage" новый метод(геттер) " Map<Long, Film> getFilms() { return films; }

2024-05-26 18:01 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public boolean idIsPresent(Long id) {
Виктор, я понял, у меня видимо замылился глаз. Прошу прощение! idIsPresent -- это метод оставляем, только давайте переименуем в isFilmExists

2024-05-27 05:53 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-06-12 05:32 UTC, merged